name: Auto Commits

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
      
      - name: Make commit
        run: |
          mkdir -p .auto-commit
          echo "$(date -Iseconds): $(uuidgen)" >> .auto-commit/activity.log
          git add .auto-commit/activity.log
          git commit -m "Auto-commit: $(date +'%Y-%m-%d %H:%M:%S')"
      
      - name: Push commit
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
